# Generated by Django 2.1.4 on 2019-02-02 19:28

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_userextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', upload_to=forum.models.get_user_directory),
        ),
    ]
